# Generated by Django 5.0.6 on 2024-05-25 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prenotazione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('data_prenotazione', models.DateField()),
                ('ora_prenotazione', models.TimeField()),
                ('email_consent', models.BooleanField(default=False)),
            ],
        ),
    ]
