# Generated by Django 5.0.6 on 2024-05-25 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prenotazioni', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prenotazione',
            name='consent_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
