# Generated by Django 5.0.6 on 2024-06-05 19:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prenotazioni', '0003_alter_prenotazione_options_prenotazione_artista'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prenotazione',
            options={},
        ),
        migrations.AlterField(
            model_name='prenotazione',
            name='artista',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='ClienteAppunti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appunto', models.TextField()),
                ('data_creazione', models.DateTimeField(auto_now_add=True)),
                ('prenotazione', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prenotazioni.prenotazione')),
            ],
            options={
                'permissions': [('can_edit_prenotazione', 'Can edit prenotazione'), ('can_delete_prenotazione', 'Can delete prenotazione')],
            },
        ),
    ]
