# Generated by Django 5.0.6 on 2024-06-06 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prenotazioni', '0004_alter_prenotazione_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prenotazione',
            old_name='artista',
            new_name='tipo',
        ),
    ]
