# Generated by Django 5.0.6 on 2024-06-06 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prenotazioni', '0005_rename_artista_prenotazione_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='prenotazione',
            name='cancellato',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='prenotazione',
            name='google_calendar_event_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='prenotazione',
            name='motivo_cancellazione',
            field=models.TextField(blank=True, null=True),
        ),
    ]
